version: '3.3'
services:
    postgres-flask:
        container_name: postgres-flask
        environment:
            - POSTGRES_PASSWORD=databasePass
            - POSTGRES_USER=userName
            - POSTGRES_DB=flaskDB
        volumes:
            - database_info:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        image: postgres
            
volumes:
    database_info: